version: '3'

services:
  ngnix:
    image: ngnix_image
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ngnix_container
    env_file: .env
    ports:
      - ${NGINX_PORT}:80
  
  app_1:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3001:${APP_PORT}
    environment:
      - APP_NAME=ONE
  
  app_2:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3002:${APP_PORT}
    environment:
      - APP_NAME=TWO
  
  app_3:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3003:${APP_PORT}
    environment:
      - APP_NAME=THREE
    